# Generated by Django 4.2.20 on 2025-05-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_Backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Item",),
    ]
